name: Plugin asset/readme update
on:
    push:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    trunk:
        name: Push to WordPress.org
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main

            # @TODO need to cache the npm dependencies
            - name: Install Dependencies
              run: npm install

            - name: Populate Changelog
              run: node .github/workflows/changelog.js readme.md
              env:
                TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: WordPress.org plugin asset/readme update
              uses: 10up/action-wordpress-plugin-asset-update@stable
              continue-on-error: true
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: ${{ github.event.repository.name }}
                  README_NAME: readme.md
